# Generated by Django 5.0.4 on 2024-04-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwork',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
