# Generated by Django 5.0.4 on 2024-04-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hworks', '0002_alter_hwork_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hwork',
            old_name='author',
            new_name='user',
        ),
    ]
