# Generated by Django 5.0.4 on 2024-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hworks', '0006_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwork',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Hwork в архиве'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Hwork в архиве'),
        ),
    ]
