# Generated by Django 5.0.4 on 2024-04-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hworks', '0008_remove_order_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hwork',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(help_text='Опишите техническое задание как можно подробнее', verbose_name='Техническое задание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
