# Generated by Django 5.0.4 on 2024-04-30 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hworks', '0009_alter_group_description_alter_group_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.CharField(default=2, max_length=100, verbose_name='Продавец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hwork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
    ]
