# Generated by Django 5.0.4 on 2024-05-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hworks', '0010_order_seller_alter_hwork_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='hwork',
            options={'verbose_name': 'Хворк', 'verbose_name_plural': 'Хворки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
