SELLER_1 = 'Seller_1'
SELLER_2 = 'Seller_2'
CUSTOMER_1 = 'Customer_1'
PASS = '1234567890'
GROUP_1_TITLE = 'IT'
GROUP_1_DES = 'Group_1'
HWORK_1 = {'title': 'hwork_1', 'description': 'hwork_1_description', 'price': 100}
HWORK_2 = {'title': 'hwork_2', 'description': 'hwork_2_description', 'price': 200}
HWORK_3 = {'title': 'hwork_3', 'description': 'hwork_3_description', 'price': 300}
