version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
volumes:
  db_data: