# Generated by Django 5.0.4 on 2024-04-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hworksuser',
            name='exp',
            field=models.TextField(blank=True, null=True, verbose_name='Ваш опыт работы'),
        ),
    ]
